# -*- coding: utf-8 -*-
"""Problem_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LVM1fr0-geTXO6Ks_tpKHBqxPTE3ZdyO
"""

#Chandrakanth
#Problem 4, coding the SVD and calculating the homography Matrix
import numpy as np
from numpy.linalg import eig
import math

#Write down our matrix
x1,x2,x3,x4,y1,y2,y3,y4,xp1,xp2,xp3,xp4,yp1,yp2,yp3,yp4 = 5,150,150,5,5,5,150,150,100,200,220,100,100,80,80,200
A = np.array([[-x1,-y1,-1,0,0,0,x1*xp1,y1*xp1,xp1],
              [0,0,0,-x1,-y1,-1,x1*yp1,y1*yp1,yp1],
              [-x2,-y2,-1,0,0,0,x2*xp2,y2*xp2,xp2],
              [0,0,0,-x2,-y2,-1,x2*yp2,y2*yp2,yp2],
              [-x3,-y3,-1,0,0,0,x3*xp3,y3*xp3,xp3],
              [0,0,0,-x3,-y3,-1,x3*yp3,y3*yp3,yp3],
              [-x4,-y4,-1,0,0,0,x4*xp4,y4*xp4,xp4],
              [0,0,0,-x4,-y4,-1,x4*yp4,y4*yp4,yp4]])
A

#calculate the AAT
C = np.dot(A,A.T)
w_1,v_1=eig(C)
eigen_values_1,eigen_vectors_1 = np.array(w_1), np.array(v_1)
sort_val = eigen_values_1.argsort()[::-1]
eigen_values_1 = eigen_values_1[sort_val]
eigen_vectors_1 = eigen_vectors_1[:,sort_val]
print(eigen_vectors_1)
#This is the U matrix

#singular values
sigma_1, sigma_2, sigma_3,sigma_4,sigma_5,sigma_6,sigma_7,sigma_8 = np.sqrt(eigen_values_1)

#create a identity matrix and then update the diagonals with the sigma values to get the sigma matrix
sigma_matrix = np.eye(8)
L = [sigma_1, sigma_2, sigma_3,sigma_4,sigma_5,sigma_6,sigma_7,sigma_8]
d = np.diag_indices_from(sigma_matrix)
sigma_matrix[d] = L
sigma_matrix

#Now let us compute AT.A and find the eigen values and vectors and arrange them.
#Arrange the eigen values in descending order and find the corresponding eigen vectors
B = np.dot(A.T,A)
w,v=eig(B)
eigen_values,eigen_vectors = np.array(w), np.array(v)
sort_val = eigen_values.argsort()[::-1]
eigen_values = eigen_values[sort_val]
eigen_vectors = eigen_vectors[:,sort_val]
print(eigen_vectors)
#This is the V Matrix

#Homography matrix
H = np.reshape(eigen_vectors[:,8],(3,3))
H

#normalize the matrix
H = H/H[2][2]

H